//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS_HostedPayment.MPS_TransactionWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mercurypay.com/", ConfigurationName="MPS_TransactionWebService.TransactionServiceSoap")]
    public interface TransactionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditPreAuthToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditPreAuthToken(MPS_HostedPayment.MPS_TransactionWebService.CreditPreAuthToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditPreAuthCaptureToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditPreAuthCaptureToken(MPS_HostedPayment.MPS_TransactionWebService.CreditPreAuthCaptureToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditSaleToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditSaleToken(MPS_HostedPayment.MPS_TransactionWebService.CreditSaleToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditVoidSaleToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditVoidSaleToken(MPS_HostedPayment.MPS_TransactionWebService.CreditVoidSaleToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditReturnToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditReturnToken(MPS_HostedPayment.MPS_TransactionWebService.CreditReturnToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditVoidReturnToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditVoidReturnToken(MPS_HostedPayment.MPS_TransactionWebService.CreditVoidReturnToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditReversalToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditReversalToken(MPS_HostedPayment.MPS_TransactionWebService.CreditReversalToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditAdjustToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditAdjustToken(MPS_HostedPayment.MPS_TransactionWebService.CreditAdjustToken request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/BatchClear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.BatchClearResponse BatchClear(MPS_HostedPayment.MPS_TransactionWebService.BatchClear request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/BatchClose", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.BatchCloseResponse BatchClose(MPS_HostedPayment.MPS_TransactionWebService.BatchClose request, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/BatchSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AdminTransactionBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CreditTransactionBase))]
        MPS_HostedPayment.MPS_TransactionWebService.BatchSummaryResponse BatchSummary(MPS_HostedPayment.MPS_TransactionWebService.BatchSummary request, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditPreAuthToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double amountField;
        
        private string invoiceField;
        
        private string addressField;
        
        private string zipField;
        
        private string cVVField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private bool partialAuthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
                this.RaisePropertyChanged("CVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool PartialAuth {
            get {
                return this.partialAuthField;
            }
            set {
                this.partialAuthField = value;
                this.RaisePropertyChanged("PartialAuth");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditAdjustToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditReversalToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditVoidReturnToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditReturnToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditVoidSaleToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditSaleToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditPreAuthCaptureToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditPreAuthToken))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditTransactionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchSummaryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string messageField;
        
        private string batchNoField;
        
        private int batchItemCountField;
        
        private double netBatchTotalField;
        
        private int creditPurchaseCountField;
        
        private double creditPurchaseAmountField;
        
        private int creditReturnCountField;
        
        private double creditReturnAmountField;
        
        private int debitPurchaseCountField;
        
        private double debitPurchaseAmountField;
        
        private int debitReturnCountField;
        
        private double debitReturnAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("BatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BatchItemCount {
            get {
                return this.batchItemCountField;
            }
            set {
                this.batchItemCountField = value;
                this.RaisePropertyChanged("BatchItemCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double NetBatchTotal {
            get {
                return this.netBatchTotalField;
            }
            set {
                this.netBatchTotalField = value;
                this.RaisePropertyChanged("NetBatchTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CreditPurchaseCount {
            get {
                return this.creditPurchaseCountField;
            }
            set {
                this.creditPurchaseCountField = value;
                this.RaisePropertyChanged("CreditPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double CreditPurchaseAmount {
            get {
                return this.creditPurchaseAmountField;
            }
            set {
                this.creditPurchaseAmountField = value;
                this.RaisePropertyChanged("CreditPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreditReturnCount {
            get {
                return this.creditReturnCountField;
            }
            set {
                this.creditReturnCountField = value;
                this.RaisePropertyChanged("CreditReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double CreditReturnAmount {
            get {
                return this.creditReturnAmountField;
            }
            set {
                this.creditReturnAmountField = value;
                this.RaisePropertyChanged("CreditReturnAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DebitPurchaseCount {
            get {
                return this.debitPurchaseCountField;
            }
            set {
                this.debitPurchaseCountField = value;
                this.RaisePropertyChanged("DebitPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double DebitPurchaseAmount {
            get {
                return this.debitPurchaseAmountField;
            }
            set {
                this.debitPurchaseAmountField = value;
                this.RaisePropertyChanged("DebitPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DebitReturnCount {
            get {
                return this.debitReturnCountField;
            }
            set {
                this.debitReturnCountField = value;
                this.RaisePropertyChanged("DebitReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double DebitReturnAmount {
            get {
                return this.debitReturnAmountField;
            }
            set {
                this.debitReturnAmountField = value;
                this.RaisePropertyChanged("DebitReturnAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchCloseResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string messageField;
        
        private string batchNoField;
        
        private int batchItemCountField;
        
        private double netBatchTotalField;
        
        private int creditPurchaseCountField;
        
        private double creditPurchaseAmountField;
        
        private int creditReturnCountField;
        
        private double creditReturnAmountField;
        
        private int debitPurchaseCountField;
        
        private double debitPurchaseAmountField;
        
        private int debitReturnCountField;
        
        private double debitReturnAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("BatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BatchItemCount {
            get {
                return this.batchItemCountField;
            }
            set {
                this.batchItemCountField = value;
                this.RaisePropertyChanged("BatchItemCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double NetBatchTotal {
            get {
                return this.netBatchTotalField;
            }
            set {
                this.netBatchTotalField = value;
                this.RaisePropertyChanged("NetBatchTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CreditPurchaseCount {
            get {
                return this.creditPurchaseCountField;
            }
            set {
                this.creditPurchaseCountField = value;
                this.RaisePropertyChanged("CreditPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double CreditPurchaseAmount {
            get {
                return this.creditPurchaseAmountField;
            }
            set {
                this.creditPurchaseAmountField = value;
                this.RaisePropertyChanged("CreditPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreditReturnCount {
            get {
                return this.creditReturnCountField;
            }
            set {
                this.creditReturnCountField = value;
                this.RaisePropertyChanged("CreditReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double CreditReturnAmount {
            get {
                return this.creditReturnAmountField;
            }
            set {
                this.creditReturnAmountField = value;
                this.RaisePropertyChanged("CreditReturnAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DebitPurchaseCount {
            get {
                return this.debitPurchaseCountField;
            }
            set {
                this.debitPurchaseCountField = value;
                this.RaisePropertyChanged("DebitPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double DebitPurchaseAmount {
            get {
                return this.debitPurchaseAmountField;
            }
            set {
                this.debitPurchaseAmountField = value;
                this.RaisePropertyChanged("DebitPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DebitReturnCount {
            get {
                return this.debitReturnCountField;
            }
            set {
                this.debitReturnCountField = value;
                this.RaisePropertyChanged("DebitReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double DebitReturnAmount {
            get {
                return this.debitReturnAmountField;
            }
            set {
                this.debitReturnAmountField = value;
                this.RaisePropertyChanged("DebitReturnAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchClearResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatchSummary))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatchClose))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BatchClear))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class AdminTransactionBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchSummary : AdminTransactionBase {
        
        private string merchantIDField;
        
        private string memoField;
        
        private string operatorIDField;
        
        private string terminalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchClose : AdminTransactionBase {
        
        private string merchantIDField;
        
        private string memoField;
        
        private string operatorIDField;
        
        private string terminalNameField;
        
        private string batchNoField;
        
        private int batchItemCountField;
        
        private double netBatchTotalField;
        
        private int creditPurchaseCountField;
        
        private double creditPurchaseAmountField;
        
        private int creditReturnCountField;
        
        private double creditReturnAmountField;
        
        private int debitPurchaseCountField;
        
        private double debitPurchaseAmountField;
        
        private int debitReturnCountField;
        
        private double debitReturnAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("BatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BatchItemCount {
            get {
                return this.batchItemCountField;
            }
            set {
                this.batchItemCountField = value;
                this.RaisePropertyChanged("BatchItemCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double NetBatchTotal {
            get {
                return this.netBatchTotalField;
            }
            set {
                this.netBatchTotalField = value;
                this.RaisePropertyChanged("NetBatchTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreditPurchaseCount {
            get {
                return this.creditPurchaseCountField;
            }
            set {
                this.creditPurchaseCountField = value;
                this.RaisePropertyChanged("CreditPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double CreditPurchaseAmount {
            get {
                return this.creditPurchaseAmountField;
            }
            set {
                this.creditPurchaseAmountField = value;
                this.RaisePropertyChanged("CreditPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CreditReturnCount {
            get {
                return this.creditReturnCountField;
            }
            set {
                this.creditReturnCountField = value;
                this.RaisePropertyChanged("CreditReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double CreditReturnAmount {
            get {
                return this.creditReturnAmountField;
            }
            set {
                this.creditReturnAmountField = value;
                this.RaisePropertyChanged("CreditReturnAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DebitPurchaseCount {
            get {
                return this.debitPurchaseCountField;
            }
            set {
                this.debitPurchaseCountField = value;
                this.RaisePropertyChanged("DebitPurchaseCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double DebitPurchaseAmount {
            get {
                return this.debitPurchaseAmountField;
            }
            set {
                this.debitPurchaseAmountField = value;
                this.RaisePropertyChanged("DebitPurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int DebitReturnCount {
            get {
                return this.debitReturnCountField;
            }
            set {
                this.debitReturnCountField = value;
                this.RaisePropertyChanged("DebitReturnCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double DebitReturnAmount {
            get {
                return this.debitReturnAmountField;
            }
            set {
                this.debitReturnAmountField = value;
                this.RaisePropertyChanged("DebitReturnAmount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class BatchClear : AdminTransactionBase {
        
        private string merchantIDField;
        
        private string memoField;
        
        private string operatorIDField;
        
        private string terminalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acqRefDataField;
        
        private string authCodeField;
        
        private string aVSResultField;
        
        private string batchNoField;
        
        private string cVVResultField;
        
        private string invoiceField;
        
        private string messageField;
        
        private string refNoField;
        
        private string statusField;
        
        private string accountField;
        
        private string cardTypeField;
        
        private string tokenField;
        
        private double authorizeAmountField;
        
        private string processDataField;
        
        private double purchaseAmountField;
        
        private double gratuityAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AcqRefData {
            get {
                return this.acqRefDataField;
            }
            set {
                this.acqRefDataField = value;
                this.RaisePropertyChanged("AcqRefData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AVSResult {
            get {
                return this.aVSResultField;
            }
            set {
                this.aVSResultField = value;
                this.RaisePropertyChanged("AVSResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("BatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CVVResult {
            get {
                return this.cVVResultField;
            }
            set {
                this.cVVResultField = value;
                this.RaisePropertyChanged("CVVResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("RefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double AuthorizeAmount {
            get {
                return this.authorizeAmountField;
            }
            set {
                this.authorizeAmountField = value;
                this.RaisePropertyChanged("AuthorizeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ProcessData {
            get {
                return this.processDataField;
            }
            set {
                this.processDataField = value;
                this.RaisePropertyChanged("ProcessData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double GratuityAmount {
            get {
                return this.gratuityAmountField;
            }
            set {
                this.gratuityAmountField = value;
                this.RaisePropertyChanged("GratuityAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditAdjustToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private string refNoField;
        
        private string invoiceField;
        
        private string memoField;
        
        private string authCodeField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string cardHolderNameField;
        
        private double gratuityAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("RefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double GratuityAmount {
            get {
                return this.gratuityAmountField;
            }
            set {
                this.gratuityAmountField = value;
                this.RaisePropertyChanged("GratuityAmount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditReversalToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private string invoiceField;
        
        private string refNoField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private string authCodeField;
        
        private string processDataField;
        
        private string acqRefDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("RefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProcessData {
            get {
                return this.processDataField;
            }
            set {
                this.processDataField = value;
                this.RaisePropertyChanged("ProcessData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AcqRefData {
            get {
                return this.acqRefDataField;
            }
            set {
                this.acqRefDataField = value;
                this.RaisePropertyChanged("AcqRefData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditVoidReturnToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private string invoiceField;
        
        private string refNoField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private string authCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("RefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditReturnToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private string invoiceField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditVoidSaleToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private string invoiceField;
        
        private string refNoField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private string authCodeField;
        
        private string processDataField;
        
        private string acqRefDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("RefNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProcessData {
            get {
                return this.processDataField;
            }
            set {
                this.processDataField = value;
                this.RaisePropertyChanged("ProcessData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AcqRefData {
            get {
                return this.acqRefDataField;
            }
            set {
                this.acqRefDataField = value;
                this.RaisePropertyChanged("AcqRefData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditSaleToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private double taxAmountField;
        
        private string customerCodeField;
        
        private string invoiceField;
        
        private string addressField;
        
        private string zipField;
        
        private string cVVField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string memoField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        private bool partialAuthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("CustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
                this.RaisePropertyChanged("CVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool PartialAuth {
            get {
                return this.partialAuthField;
            }
            set {
                this.partialAuthField = value;
                this.RaisePropertyChanged("PartialAuth");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CreditPreAuthCaptureToken : CreditTransactionBase {
        
        private string merchantIDField;
        
        private double purchaseAmountField;
        
        private double authorizeAmountField;
        
        private double gratuityAmountField;
        
        private double taxAmountField;
        
        private string customerCodeField;
        
        private string invoiceField;
        
        private string authCodeField;
        
        private string acqRefDataField;
        
        private string memoField;
        
        private string terminalNameField;
        
        private string operatorIDField;
        
        private string cardHolderNameField;
        
        private string tokenField;
        
        private string frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
                this.RaisePropertyChanged("MerchantID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double PurchaseAmount {
            get {
                return this.purchaseAmountField;
            }
            set {
                this.purchaseAmountField = value;
                this.RaisePropertyChanged("PurchaseAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double AuthorizeAmount {
            get {
                return this.authorizeAmountField;
            }
            set {
                this.authorizeAmountField = value;
                this.RaisePropertyChanged("AuthorizeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double GratuityAmount {
            get {
                return this.gratuityAmountField;
            }
            set {
                this.gratuityAmountField = value;
                this.RaisePropertyChanged("GratuityAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("TaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("CustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("Invoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AcqRefData {
            get {
                return this.acqRefDataField;
            }
            set {
                this.acqRefDataField = value;
                this.RaisePropertyChanged("AcqRefData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
                this.RaisePropertyChanged("CardHolderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionServiceSoapChannel : MPS_HostedPayment.MPS_TransactionWebService.TransactionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceSoapClient : System.ServiceModel.ClientBase<MPS_HostedPayment.MPS_TransactionWebService.TransactionServiceSoap>, MPS_HostedPayment.MPS_TransactionWebService.TransactionServiceSoap {
        
        public TransactionServiceSoapClient() {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditPreAuthToken(MPS_HostedPayment.MPS_TransactionWebService.CreditPreAuthToken request, string password) {
            return base.Channel.CreditPreAuthToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditPreAuthCaptureToken(MPS_HostedPayment.MPS_TransactionWebService.CreditPreAuthCaptureToken request, string password) {
            return base.Channel.CreditPreAuthCaptureToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditSaleToken(MPS_HostedPayment.MPS_TransactionWebService.CreditSaleToken request, string password) {
            return base.Channel.CreditSaleToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditVoidSaleToken(MPS_HostedPayment.MPS_TransactionWebService.CreditVoidSaleToken request, string password) {
            return base.Channel.CreditVoidSaleToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditReturnToken(MPS_HostedPayment.MPS_TransactionWebService.CreditReturnToken request, string password) {
            return base.Channel.CreditReturnToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditVoidReturnToken(MPS_HostedPayment.MPS_TransactionWebService.CreditVoidReturnToken request, string password) {
            return base.Channel.CreditVoidReturnToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditReversalToken(MPS_HostedPayment.MPS_TransactionWebService.CreditReversalToken request, string password) {
            return base.Channel.CreditReversalToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.CreditResponse CreditAdjustToken(MPS_HostedPayment.MPS_TransactionWebService.CreditAdjustToken request, string password) {
            return base.Channel.CreditAdjustToken(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.BatchClearResponse BatchClear(MPS_HostedPayment.MPS_TransactionWebService.BatchClear request, string password) {
            return base.Channel.BatchClear(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.BatchCloseResponse BatchClose(MPS_HostedPayment.MPS_TransactionWebService.BatchClose request, string password) {
            return base.Channel.BatchClose(request, password);
        }
        
        public MPS_HostedPayment.MPS_TransactionWebService.BatchSummaryResponse BatchSummary(MPS_HostedPayment.MPS_TransactionWebService.BatchSummary request, string password) {
            return base.Channel.BatchSummary(request, password);
        }
    }
}
